### ISSUE TITLE
AWS Native API doc examples don't have helpful headers

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws-native#891] opened 2023-04-06 17:01 UTC
If I look at AWS Native's S3 bucket examples, they are all titled simply "Example":

![image](https://user-images.githubusercontent.com/3953235/230446490-0427d50c-2277-412b-b0cb-9ab3b61b0c45.png)

Compare to AWS Classic:

![image](https://user-images.githubusercontent.com/3953235/230446551-2cb539dc-3678-4e3d-b428-48c41e6d1a83.png)

Are we dropping useful descriptions of them somewhere?

**Comment by lukehoban** [comment] 2023-04-26 05:05
Duplicate of #826. 

As noted there - the title is currently hardcoded to “Example”.  Definitely needs to be fixed before GA.

**Closed by lukehoban** 2023-04-26 05:05 UTC
Labels: kind/enhancement, resolution/duplicate, impact/usability, area/docs
