### ISSUE TITLE
APIs are missing some documentation

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws-native#1336] opened 2024-02-10 18:24 UTC
I'm unsure if this is intentional, but a number of the resources have missing property documentation. For example, this type is missing it entirely (https://www.pulumi.com/registry/packages/awsx/api-docs/ecs/fargateservice/#taskdefinitionlogconfiguration) but if you scroll around the page, there are partly documented types too.

**Comment by mikhailshilkov** [comment] 2024-03-27 08:36
@mjeffryes It looks like the aws-native provider descriptions are fixed in this particular place, see https://www.pulumi.com/registry/packages/aws-native/api-docs/ecs/taskdefinition/#taskdefinitionlogconfiguration

Is it a matter of releasing a new version of awsx now to fix the issue reported by Joe?

Also, let's either find a new example of missing descriptions and update this issue, or close it if the problem is truly fixed now.

**Closed** 2024-06-17 21:59 UTC
Labels: kind/enhancement, resolution/fixed, area/docs
