### ISSUE TITLE
aws-native:iotwireless:DeviceProfile property name changed

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws-native#1050] opened 2023-08-24 20:13 UTC
### What happened?

Previously the property `loRaWan` was typed as `loRaWAN`

At some point, that property name changed its casing.

As a result, customers have to modify their code to match, which causes an update:

```
 ~   ├─ aws-native:iotwireless:DeviceProfile   <redacted>  update     [diff: +loRaWan-loRaWAN]
 ~   ├─ aws-native:iotwireless:DeviceProfile   <redacted>  update     [diff: +loRaWan-loRaWAN]
 ~   ├─ aws-native:iotwireless:ServiceProfile  <redacted>       update     [diff: +loRaWan-loRaWAN]
 ~   └─ aws-native:iotwireless:DeviceProfile   <redacted>  update     [diff: +loRaWan-loRaWAN]
```

Unfortunately this throws an error:

```
  aws-native:iotwireless:DeviceProfile (<redacted>):
    error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID:redacted, UnsupportedActionException: Resource type AWS::IoTWireless::DeviceProfile does not support UPDATE action
```

### Expected Behavior

Either the API shape doesn't change, or the property can easily be aliased

### Steps to reproduce

I'm not sure when the property changed, but creating a resource with an old provider and updating will likely showcase it

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2023-08-25 13:00
@jaxxstorm which version of the provider are you moving from and to?

Does the diff go away if a refresh is performed first?

**Comment by mikhailshilkov** [comment] 2023-08-25 14:51
I believe this is by design - changed in https://github.com/pulumi/pulumi-aws-native/pull/999 cc @mjeffryes 

I don't think we have property-level aliasing?

**Comment by danielrbradley** [comment] 2023-08-25 14:58
No we don't have any concept of property aliases. Here's the issue tracking that:
- https://github.com/pulumi/pulumi/issues/9115

It's currently something that would have to be implemented on a per-provider basis because the engine doesn't do the diff for most providers and isn't (yet) schema aware.

**Comment by jaxxstorm** [comment] 2023-08-26 00:23
@danielrbradley i don't have the exact versions I'm afraid.

A refresh doesn't resolve this, no. It actually halts the program and requires deleting and recreating the resource

**Comment by mjeffryes** [comment] 2023-08-28 22:11
Yes, we agreed to make a breaking change with #999 since this provider is still in preview. It is a pretty significant breaking change that will force some updates and replacements just to resolve the naming changes.

The error you encountered in update is due to #736; the workaround is manually adding `replaceOnChanges` to `DeviceProfile`.

**Comment by mikhailshilkov** [comment] 2023-09-14 10:23
I'll close it by design, I'm sorry for inflicting pain on users, but better do it now on preview than later

**Closed by mikhailshilkov** 2023-09-14 10:23 UTC
Labels: kind/bug, resolution/by-design
