### ISSUE TITLE
Not all packages/modules have the docs published in the reference docs.

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-aws-native#180] opened 2021-10-17 17:09 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Not all modules have the docs published in the reference docs.

### Steps to reproduce

1. Open https://www.pulumi.com/docs/reference/pkg/aws-native/
2. Verify that modules `codebuild` and `codepipeline` **are not** in this list
3. Open https://github.com/pulumi/pulumi-aws-native/tree/master/sdk/nodejs
4. See that folders `codebuild` and `codepipeline` **are** in this list.

Expected: all packages in the SDK to have corresponding documentation in the API reference docs.
Actual: not all packages in the SDK have browsable API documentation.

**Comment by mikhailshilkov** [comment] 2021-10-17 19:23
Hey @ringods 

This is by design. None of the resources in those folders are currently supported by AWS Cloud Control API, so they don't actually work. There's no point specifying them in docs IMO.

We still generate the SDK types for them to "preview" the shapes of those resources, make sure our codegen handles them well, and support cf2pulumi.

**Comment by mikhailshilkov** [comment] 2021-11-15 15:42
Closing as there's nothing we need to track for this

**Closed by mikhailshilkov** 2021-11-15 15:42 UTC
Labels: resolution/fixed, kind/bug
