### ISSUE TITLE
Fail to grant Lakaformtion permissions

### ISSUE THREAD

**Issue by piotrlinski** [pulumi/pulumi-aws-native#1303] opened 2024-01-31 07:36 UTC
### What happened?

"pulumi up" failed to deploy Lakeformation permissions for Glue resource (in example I use database, however all resources are affected). I have tried to with cli as well as automation API. In any case I can see similar behavior.

Below output from cli execution

run "pulumi up" for the first time (resource is created, but not added to stack state)

```
Diagnostics:
  pulumi:pulumi:Stack (xxx-xxx):
    error: update failed

  aws-native:lakeformation:PrincipalPermissions (some_database__some_table):
    error: reading resource state: reading resource state: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: d655967a-df71-434a-9053-178904231ede, api error ValidationException: When specifying the identifier as JSON, you must specify exactly one identifier from [[/properties/PrincipalIdentifier, /properties/ResourceIdentifier]], and no additional properties can be specified

```
run "pulumi up" for the second time (resource is created already, but not added to the stack state, the create resource call is invoked most probably, in result the alredy exists error is raised)

```
Diagnostics:
  aws-native:lakeformation:PrincipalPermissions (principalPermissions):
    error: operation CREATE failed with "AlreadyExists": Resource of type 'AWS::LakeFormation::PrincipalPermissions' with identifier '1xZiwxnNnD7HvELxOA9rR0xmm' already exists.

```

------------------

and automation api program invocation

```
Updating (engineering):

    pulumi:pulumi:Stack xxx running
@ updating.....
 +  aws-native:lakeformation:PrincipalPermissions some_database__some_table creating (0s)
@ updating............
 +  aws-native:lakeformation:PrincipalPermissions some_database__some_table creating (9s) error: operation CREATE failed with "AlreadyExists": Resource of type 'AWS::LakeFormation::PrincipalPermissions' with identifier 'Cn6or3bPAOfiNj06PitpTHzPX' already exists.
 +  aws-native:lakeformation:PrincipalPermissions some_database__some_table **creating failed** error: operation CREATE failed with "AlreadyExists": Resource of type 'AWS::LakeFormation::PrincipalPermissions' with identifier 'Cn6or3bPAOfiNj06PitpTHzPX' already exists.
    pulumi:pulumi:Stack xxx running error: update failed
@ updating.......
    pulumi:pulumi:Stack xxx-xxx **failed** 1 error
Diagnostics:
  pulumi:pulumi:Stack (xxx-xxx):
    error: update failed

  aws-native:lakeformation:PrincipalPermissions (esome_database__some_table):
    error: operation CREATE failed with "AlreadyExists": Resource of type 'AWS::LakeFormation::PrincipalPermissions' with identifier 'Cn6or3bPAOfiNj06PitpTHzPX' already exists.

Resources:
    1 unchanged

Duration: 12s
```

### Example

```
from pulumi_aws_native import lakeformation

principal_permissions = lakeformation.PrincipalPermissions(
    resource_name="principalPermissions",
    catalog="123456789012",
    permissions=["SELECT"],
    principal={
        "dataLakePrincipalIdentifier": "arn:aws:iam::123456789012:role/some-role",
    },
    resource={
        "table": {
            "databaseName": "some_database",
            "name": "some_table",
            "catalogId": "123456789012"
        }
    },
    permissions_with_grant_option=["SELECT"]
)
```

### Output of `pulumi about`

Enter your passphrase to unlock config/secrets
CLI
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.19.0
aws-native  0.95.0
python      unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/Users/xxx/xxx/xxx/venv/bin/python3' version='3.9.13'

Current Stack: organization/lf-check/dev

TYPE                         URN
pulumi:pulumi:Stack          urn:pulumi:dev::lf-check::pulumi:pulumi:Stack::lf-check-dev
pulumi:providers:aws-native  urn:pulumi:dev::lf-check::pulumi:providers:aws-native::default_0_95_0
pulumi:providers:aws-native  urn:pulumi:dev::lf-check::pulumi:providers:aws-native::default

Found no pending operations associated with dev

Backend
Name           xxx-mbp.home
URL            s3://xxx/pulumi2
User           xxx
Organizations
Token type     personal

Dependencies:
NAME                       VERSION
install                    1.3.5
pip                        23.2.1
pulumi_aws                 6.19.0
pulumi-aws-native          0.95.0
setuptools                 68.2.0
wheel                      0.41.2

Pulumi locates its logs in /var/folders/0v/_6rzvd4s2lv1rjmc3v_y8nsw0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment] 2024-02-01 01:02
Thank you for filing this issue @piotrlinski. Looks like we're generating an invalid read request to the resource after creation. 

To debug, we'll need to try to reproduce with verbose logging to extract the API request cloud control is complaining about and then try to determine how the request needs to be changed to satisfy the API.

**Comment by piotrlinski** [comment] 2024-02-01 07:43
This is not me generating the invalid request. I am pretty sure that the issue is related to this one https://github.com/pulumi/pulumi-aws-native/issues/648. The flow goes like this:

1. pulumi sends request to CloudControlApi to create permissions
2. then pulumi wants to verify if the resource is created - sent request GET resource - but the request is invalid, thus can not verify if resource is created, resource is not added to a state, and ...... 

I have run my code with debugging enabled and high logging verbosity, this is what comes up - same log I have provided 

```
error: reading resource state: reading resource state: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: d655967a-df71-434a-9053-178904231ede, api error ValidationException: When specifying the identifier as JSON, you must specify exactly one identifier from [[/properties/PrincipalIdentifier, /properties/ResourceIdentifier]], and no additional properties can be specified
```

This is not an issue of pulumi, this is CloudControlApi issue. Now the question is if pulumi can solve it on its end

**Comment by piotrlinski** [comment] 2024-02-02 07:18
Here is the python which does exactly thing we need 

```
from boto3.session import Session

session = Session()
client = session.client('cloudcontrol')


principal_identifier = {
    "DataLakePrincipalIdentifier": "arn:aws:iam::123456789012:role/some_role"
}

resource_identifier = {
    'Database': {
        'CatalogId': '123456789012',
        'Name': 'some_database'
    }
}

create_resource_json = {
  "Catalog": "123456789012",
  "Permissions": ["ALL"],
  "PermissionsWithGrantOption": ["ALL"],
  "Principal": principal_identifier,
  "Resource": resource_identifier
}

response = client.create_resource(
    TypeName='AWS::LakeFormation::PrincipalPermissions',
    DesiredState=json.dumps(create_resource_json)
)
print(response)

response = client.get_resource_request_status(
    RequestToken=response['ProgressEvent']['RequestToken']
)
print(response)

get_resource_json = {
    "PrincipalIdentifier": json.dumps(principal_identifier),
    "ResourceIdentifier": json.dumps(resource_identifier)
}

response = client.get_resource(
    TypeName='AWS::LakeFormation::PrincipalPermissions',
    Identifier=json.dumps(get_resource_json)
)
print(response)
```

**Comment by mikhailshilkov** [comment] 2024-03-08 23:06
Looks like a duplicate of https://github.com/pulumi/pulumi-aws-native/issues/648 indeed. Let's track it over there.

**Closed by mikhailshilkov** 2024-03-08 23:06 UTC
Labels: resolution/duplicate, kind/bug, area/codegen
