### ISSUE TITLE
Dynamodb createTable keySchema does not match with specification

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#728] opened 2022-12-07 08:08 UTC
### What happened?

Creating a dynamodb table with the AWS native library does not succeed as the content of the keySchema is not converted to uppercase for AWS.

Lib version used: 0.43.0

### Steps to reproduce

```
const table = new aws.dynamodb.Table("table", {
  attributeDefinitions: [
    {
      attributeName: "test",
      attributeType: "S",
    },
    {
      attributeName: "Part",
      attributeType: "S",
    },
  ],
  keySchema: [
    {
      attributeName: "test", // <-- this must be uppercase currently to not get an error on this part.
      keyType: "HASH",
    },
    {
      attributeName: "Part",
      keyType: "RANGE",
    },
  ],
  tableName: "table",
  billingMode: "PAY_PER_REQUEST",
});
```

### Expected Behavior

As the pulumi documentation indicates, `attributeName` and `keyType` should be written as such and not with uppercase.

### Actual Behavior

```
 aws-native:dynamodb:Table (healthcare-providers):
    error: creating resource: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID: 60c33dc6-3a65-4bf8-88ed-adbf151f9800, api error ValidationException: Model validation failed (#/KeySchema: #: 0 subschemas matched instead of one
    #/KeySchema/0: required key [KeyType] not found
    #/KeySchema/0: required key [AttributeName] not found
    #/KeySchema/0: extraneous key [attributeName] is not permitted
    #/KeySchema/0: extraneous key [keyType] is not permitted
    #/KeySchema/1: required key [KeyType] not found
    #/KeySchema/1: required key [AttributeName] not found
    #/KeySchema/1: extraneous key [attributeName] is not permitted
    #/KeySchema/1: extraneous key [keyType] is not permitted
    #/KeySchema: expected type: JSONObject, found: JSONArray)
```

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws         5.23.0
@pulumi/aws-native  0.43.0
@pulumi/pulumi      3.48.0
```

### Additional context

When I convert the letters into uppercase, the error disappears.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment] 2022-12-07 15:48
Hi @Jimmy89, thanks for the issue! I believe you're correct, and AWS is expecting the first letter of these keys to be capitalised. I've raised this with the team to be prioritized and added to our work stack.

**Comment by danielrbradley** [comment] 2022-12-07 17:19
These propety names should be automatically converted if they're typed. For reference, here's where the conversion is defined: https://github.com/pulumi/pulumi-aws-native/blob/bf65486a90ae7e1ef88da2435c4a9ba6efe175f2/provider/pkg/schema/convert.go#L51-L79

I assume the `attributeName` is fully typed and not just defined as `any`?

**Comment by Jimmy89** [comment] 2023-01-19 13:09
@danielrbradley any update on this issue? If I update the table to enable pointInTimeRecoverySpecification I get the error that `attributeName` (with lowercase) cannot be found and seems there is no workaround currently.

**Comment by Jimmy89** [comment] 2023-02-13 09:02
@roothorp is there an indication when this issue will be picked up, as it blocks/annoys the creation and update of any dynamodb resource.

**Comment by RobCannon** [comment] 2023-02-13 14:13
This is the last straw for me.  I have stopped trying to use the aws_native provider as there are TOO many issues like this and too many missing features that cause headaches.  I am porting everything back to the aws classic provider.

**Comment by danielrbradley** [comment] 2023-02-27 13:50
@RobCannon sorry for any fustration caused on this issue. The AWS Native provider is currently still in preview while we're still ironing out these kinds of issues and I'd recommend sticking with the classic provider until this reaches a point of general availability. We appreciate you working with us on resolving these issues and hopefully this new provider will reach parity of features in the near future.

**Comment by danielrbradley** [comment] 2023-02-27 13:57
@Jimmy89 I'm digging into this again. One theory is it might be related to the definitions showing this a either being of type `any` or the defined type. When working with known types, we expect to do case conversion, but when it's an `any` type, we just pass it as-is. This is then a little unclear on the behaviour when either can be used for the same property. The next step is to confirm this with a more comprehensive test and then propose a resolution. One aspect we need to be careful with is avoiding regressions in other resources.

The workaround right now is to specify the key schema using upper-case properties which is allowed because the key schema is defined as `inputs.dynamodb.TableKeySchemaArgs[] | any` - so this just falls back to the `any` version. The downside here is that you'll loose type checking, but this should allow you to continue working (I've tested this on v0.44.0).

**Closed** 2023-02-27 20:34 UTC
Labels: kind/bug, impact/usability
